frappe.tour["Subscription"] = {
	"fr": [
		{
			fieldname: "customer",
			description: "Client auquel s'applique cet abonnement",
			next_step_tab: "venue_management_tab"
		},
		{
			previous_step_tab: "__details",
			fieldname: "booking_credits_allocation",
			description: `Permet de définir des règles d'allocation de crédits de réservation.<br>
				- Sélectionnez un type de crédit de réservation.<br>
				- Indiquez la quantité à allouer.<br>
				- Indiquez une règle de récurrence. Les crédits seront alloués selon cette règle.<br>
				- Indiquez une durée avant expiration
			`
		}
	]
}

// frappe.tour["Subscription"] = [
// 	{
// 		fieldname: "customer",
// 		title: __("Customer"),
// 		description: __("Select the customer that will be associated with this subscription."),
// 	},
// 	{
// 		fieldname: "company",
// 		title: "Company",
// 		description: "Indicate the company assigned to the subscription. This field is important if your Dokos instance manages several companies.",
// 	},
// 	{
// 		fieldname: "start",
// 		title: "Start date of the subscription",
// 		description: "Set the start date of the subscription.",
// 	},
// 	{
// 		fieldname: "subscription_period",
// 		title: "Subscription Period",
// 		description: "In this section you can define several dates. The start date of the subscription, the start of the trial period, the start date of the current billing period and the start date of the current billing period.",
// 	},
// 	{
// 		fieldname: "create_sales_order",
// 		title: "Generate a sales order at beginning Of period",
// 		description: "If the box is checked, then a sales order will be generated at the beginning of the period.",
// 	},
// 	{
// 		fieldname: "generate_invoice_at_period_start",
// 		title: "Submit invoice automatically",
// 		description: "If the box is checked, then a sales invoice will be generated at the beginning of the period.",
// 	},
// 	{
// 		fieldname: "submit_invoice",
// 		title: "Submit invoice automatically",
// 		description: "If the box is checked, then the invoice will be automatically validated when it is edited.",
// 	},
// 	{
// 		fieldname: "generate_payment_request",
// 		title: "Generate a payment request automatically",
// 		description: "If the box is checked, then a payment request will be generated automatically.",
// 	},
// 	{
// 		fieldname: "billing_interval",
// 		title: "Billing Interval",
// 		description: "Set the billing interval for this subscription. Choose between billing by Day, Week, Month or Year.",
// 	},
// 	{
// 		fieldname: "billing_interval_count",
// 		title: "Billing Interval Count",
// 		description: "Define a billing frequency. By default this value is 1. This corresponds to one invoice per interval. For example, if you specify a frequency of 2 with a monthly interval then there will be 2 invoices per month.",
// 	},
// 	{
// 		fieldname: "days_until_due",
// 		title: "Days Until Due",
// 		description: "Maximum number of days the subscriber can pay the bills generated by this subscription before being considered late.",
// 	},
// 	{
// 		fieldname: "subscription_plan",
// 		title: "Subscription Plan",
// 		description: "Define a subscription plan for your new subscription. This is to use a subscription format that you have already defined in 'Location > Subscription > Subscription plan'. The subscription plan allows you to edit subscriptions more quickly by using a plan that you have designed.",
// 	},
// 	{
// 		fieldname: "plans",
// 		title: "Plans",
// 		description: "In the Plans table, indicate the items and quantities that will be part of the subscription. Add the quantities. The price will be generated automatically if a price list has been created for the item. Note: You can change the price yourself. Go to 'Edit > Pricing > Fixed unit price.",
// 	},
// 	{
// 		fieldname: "tax_template",
// 		title: "Sales Taxes and Charges Template",
// 		description: "This is where you indicate the taxes and sales charges that will be applied to the items you sell. For example, the item will be taxed at 20% (VAT collected at 20%).",
// 	},
// 	{
// 		fieldname: "shipping_rule",
// 		title: "Shipping Rule",
// 		description: "Choose a shipping rule template. It allows you to define the cost of delivering the product to the customer.You can define different shipping rules or a fixed shipping amount for the same item in different territories.",
// 	},
// 	{
// 		fieldname: "apply_additional_discount",
// 		title: "Apply Additional Discount On",
// 		description: "Choose if you want to make a discount on the total TTC or the total HT of the subscription.",
// 	},
// 	{
// 		fieldname: "additional_discount_percentage",
// 		title: "Additional DIscount Percentage",
// 		description: "Indicate the additional discount percentage or a discount amount (in the next field).",
// 	},
// 	{
// 		fieldname: "additional_discount_amount",
// 		title: "Additional DIscount Amount",
// 		description: "Indicate the amount discount percentage or a discount percentage (in the previous field).",
// 	},
// 	{
// 		fieldname: "terms_and_conditions",
// 		title: "Terms and conditions",
// 		description: "Specify a Terms and Conditions template for this subscription",
// 	}
// ]